# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk  # "rootpassword" en base64
  MYSQL_DATABASE: Z2xwaQ==               # "glpi" en base64
  MYSQL_USER: Z2xwaV91c2Vy               # "glpi_user" en base64
  MYSQL_PASSWORD: Z2xwaV9wYXNzd29yZA==   # "glpi_password" en base64
